// export const MODULE = '/cbms-service'
import {getGlobalVariable} from '../../utils';

export const CBMS_MODULE = '';
export const CONTRACTOR_NAME_SEARCH = 'TA autotest 156';
export const URL_BASE = 'http://localhost:8080';
export const URL_BE_BASE = 'http://localhost:8102';
// export const URL = 'https://cscm.congtrinhviettel.com.vn';
export const ROUTES = {
  PURCHASE_PROPOSAL: '/CBMS_PURCHASE_PROPOSAL_NEW',
  COST_SUBMISSION: '/CBMS_COST_SUBMISSION_SHEET_N',
  KHLCNT: '/CBMS_CONTRACTOR_SELECTION_PLAN',
  KHLCNT_PURCHASE: '/CBMS_CONTRACTOR_SELECTION_PLAN_PURCHASE',
  DOCUMENT_BY_PID: '/CBMS_DOCUMENT_BY_PID',
  DOCUMENT_BY_PID_PURCHASE: '/CBMS_DOCUMENT_BY_PID_PURCHASE',
  BID_EVALUATION: '/CBMS_BID_EVALUATION/INVEST',
  BID_EVALUATION_PURCHASE: '/CBMS_BID_EVALUATION/PURCHASE'
}

export enum CONTRACTOR_STATUS {
  NEW = 'NEW',
  APPRAISED = 'APPRAISED',
  ADJUSTMENT = 'ADJUSTMENT',
  VERIFIED_DOCUMENT_BY_PID_V1 = 'VERIFIED_DOCUMENT_BY_PID_V1',
  EVALUATED = 'EVALUATED',
  VERIFIED_DOCUMENT_BY_PID_V2 = 'VERIFIED_DOCUMENT_BY_PID_V2',
}